#from __main__ import app
from common import *
from config import *

@app.route('/jenkinsdeploy')
def jenkinsdeploy():
    return render_template('jenkins/jenkins-deploy.html')

@app.route('/jenkinsload')
def jenkinsload():
    return render_template('jenkins/jenkins-loader.html')

@app.route('/jenkins')
def  jenkins():
      command="oc new-app https://github.com/alyarctiq/dashai-jenkins --name=dashai-jenkins --config="+session['kubeconfig']
      p = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
      (cmd, err) = p.communicate()
      out1=prettyprint(cmd)
      command="oc expose svc dashai-jenkins --config="+session['kubeconfig']
      p = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
      (cmd, err) = p.communicate()
      out2 = cmd
      command="oc get routes dashai-influxdb -o template --template {{.spec.host}} --config="+session['kubeconfig']
      p = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
      (cmd, err) = p.communicate()
      out3 = cmd
      out4 = """
      Once Deployed Please Do The Following to enable DashAi Integration \n
      --> In Jenkins, go to Manage Jenkins > Configure System and click new InfluxDB target.\n
      --> Provide the database information to Jenkins [eg: dashai-jenkins ].\n
      --> The url parameter needs the whole url of the influxDB database, including the http://.\n
      --> URL will be displayed below.\n
      --> Exceptions generated by InfluxDB plugin can also be ignored by unselecting the exposeExceptions checkbox \n
      --> In your job, select Publish build data to InfluxDb target from the post-build actions. \n
      """
      out4=prettyprint(out4)
      command="oc get routes dashai-jenkins -o template --template {{.spec.host}} --config="+session['kubeconfig']
      p = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
      (cmd, err) = p.communicate()
      out5 = cmd
      eventgen("Deployed Jenkins with InfluxDB Plugin")
      return render_template('jenkins/jenkins.html',
                             out1=out1,
                             out2=out2,
                             out3=out3,
                             out4=out4,
                             out5=out5
                             )
